[package]
name = "stwo_custom_air"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
stwo-prover.workspace = true
num-traits.workspace = true
itertools.workspace = true